on: [ push ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_PASSWORD --password-stdin 
      - run: docker build -t fast-api .
      - run: docker tag fast-api $DOCKER_USERNAME/fast-api:latest
      - run: docker push $DOCKER_USERNAME/fast-api:latest
